let docs=[],activeFilter='all';
const list=document.getElementById('documentList');
function size(n){if(!n)return'0 Bytes';const u=['Bytes','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return `${+(n/1024**i).toFixed(2)} ${u[i]}`;}
function typeOf(d){const e=(d.file_type||'').toLowerCase();if(['jpg','jpeg','png','gif','webp'].includes(e))return'image';if(e==='pdf')return'pdf';if(['xls','xlsx'].includes(e))return'excel';if(['doc','docx'].includes(e))return'word';if(e==='csv')return'csv';return'other';}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function row(d){const t=typeOf(d);const date=new Date(d.created_at).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});return `<div class="document-row" data-type="${t}"><div class="file-icon ${t}">${t==='image'?'IMG':t.toUpperCase()}</div><div class="file-details"><strong>${esc(d.original_name||d.name)}</strong><span>${t.toUpperCase()} · ${size(d.file_size)}</span></div><div class="file-date">${date}</div><div class="file-actions"><button title="View" onclick="viewDocument('${d.id}')">👁</button><button title="Download" onclick="downloadDocument('${d.id}')">↓</button><button title="Favorite" onclick="toggleFavorite('${d.id}')">${d.is_favorite?'★':'☆'}</button></div></div>`;}
function render(){let filtered=docs.filter(d=>!d.is_deleted&&(activeFilter==='all'||typeOf(d)===activeFilter));const q=(document.getElementById('dashboardSearch')?.value||'').toLowerCase();filtered=filtered.filter(d=>(d.original_name||d.name).toLowerCase().includes(q));const sort=document.getElementById('sortDocuments')?.value||'recent';filtered.sort((a,b)=>sort==='name'?String(a.original_name).localeCompare(String(b.original_name)):sort==='size'?(b.file_size-a.file_size):sort==='oldest'?new Date(a.created_at)-new Date(b.created_at):new Date(b.created_at)-new Date(a.created_at));list.innerHTML=filtered.length?filtered.map(row).join(''):`<div class="empty-state"><h3>${docs.filter(d=>!d.is_deleted).length?'No matching documents':'No documents yet'}</h3><p>${docs.filter(d=>!d.is_deleted).length?'Try another search or filter.':'Upload your first document to see it here.'}</p>${!docs.filter(d=>!d.is_deleted).length?'<a class="upload-btn" href="upload.html">Upload Document</a>':''}</div>`;}
async function load(){const session=await requireAuth();if(!session)return;const profile=session.profile;document.getElementById('userName').textContent=profile.name||session.user.email;document.getElementById('userRole').textContent=profile.role||'User';document.getElementById('userAvatar').textContent=(profile.name||'U')[0].toUpperCase();docs=await DocuFirebase.getDocuments();const active=docs.filter(d=>!d.is_deleted);document.getElementById('totalDocuments').textContent=active.length;document.getElementById('storageUsed').textContent=size(active.reduce((a,d)=>a+(d.file_size||0),0));document.getElementById('totalImages').textContent=active.filter(d=>typeOf(d)==='image').length;document.getElementById('totalPDFs').textContent=active.filter(d=>typeOf(d)==='pdf').length;render();}
async function downloadDocument(id){try{const url=await DocuFirebase.getDownloadUrl(id);const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.download='';document.body.appendChild(a);a.click();a.remove();}catch(e){alert(e.message);}}
function viewDocument(id){location.href=`view.html?id=${encodeURIComponent(id)}`;}
async function toggleFavorite(id){try{await DocuFirebase.toggleFavorite(id);await load();}catch(e){alert(e.message);}}
document.getElementById('logoutLink')?.addEventListener('click',e=>{e.preventDefault();logout()});document.getElementById('dashboardSearch')?.addEventListener('input',render);document.getElementById('sortDocuments')?.addEventListener('change',render);document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render();}));document.getElementById('mobileMenu')?.addEventListener('click',()=>document.getElementById('sidebar')?.classList.toggle('mobile-open'));load().catch(e=>{console.error(e);alert(e.message||'Failed to load documents.');});
